### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Conan1996-2** [Penqle/tortoise-wow#259]
On Ubuntu 24.04lts with everything pre installed:
sudo apt install -y \
git cmake build-essential clang \
libssl-dev libbz2-dev libreadline-dev \
libncurses-dev libboost-all-dev \
libmysqlclient-dev mariadb-server \
libace-dev

after using:
cmake .. \
-DCMAKE_INSTALL_PREFIX=~/twow/tortoise-wow/server \
-DBUILD_EXTRACTORS=ON \
-DBUILD_TOOLS=ON \
-DBUILD_AHBOT=ON \
-DUSE_ANTICHEAT=OFF \
-DALLOW_TURTLE_ADDONS=ON

I get the error while compiling with "make -j 4":
In file included from /home/internet/GameServers/WOW/turtlewow/source/src/framework/Policies/ObjectLifeTime.cpp:23:
In file included from /home/internet/GameServers/WOW/turtlewow/source/src/framework/Policies/ObjectLifeTime.h:26:
In file included from /home/internet/GameServers/WOW/turtlewow/source/src/framework/Platform/Define.h:34:
/home/internet/GameServers/WOW/turtlewow/source/src/shared/AllocatorWithCategory.h:79:2: error: no matching function for call to 'operator delete'
   79 |         ::operator delete(Ptr, Bytes, std::align_val_t{ alignment });

**Comment by mserajnik** [comment]
This is a compiler issue: you are building with Clang 18 (the default on Ubuntu 24.04), which does not enable sized deallocation by default.

The problem lies here: https://github.com/Penqle/tortoise-wow/blob/78698bc0eb14a9ca6535c42b23b06bcb96ddab5c/src/shared/AllocatorWithCategory.h#L79

This requires `-fsized-deallocation`. GCC enables that by default since C++14, Clang only since version 19, so the overload is never declared and the call fails to resolve.

I was able to reproduce your exact error in a clean Ubuntu 24.04 container; any one of these fixes it:

- Build with GCC instead of Clang (simplest; `build-essential` already provides it).
- Keep Clang 18 but add `-DCMAKE_CXX_FLAGS="-fsized-deallocation"` to your CMake invocation.
- Use Clang 19 (`clang-19` is available on 24.04), where sized deallocation is on by default.

Two side notes on your build setup:

- `-DBUILD_EXTRACTORS`, `-DBUILD_TOOLS` and `-DBUILD_AHBOT` do not exist in Tortoise-WoW and are silently ignored (the extractor flag is `-DUSE_EXTRACTORS=ON`, and there is no implemented AHBot at this point).
- Boost, Readline and ncurses are not used by Tortoise-WoW at all, and bzip2 is vendored in-tree, so none of them need to be installed.

If you want a reference, I am maintaining a [Docker setup with prebuilt images](https://github.com/mserajnik/tortoise-deploy). I build with GCC on Ubuntu 26.04, you can find the exact `cmake` invocation [here](https://github.com/mserajnik/tortoise-deploy/blob/072f1d36df08f0766b55b2a81aa9a73c4e8c5f4f/docker/server/Dockerfile#L83-L89).

**Comment by Conan1996-2** [comment]
Perfect ill give it a shot, thanks. I cloned the repository and started to make changes that worked like deleteing both templates with delete and making one:

template<size_t alignment>
void InternalDeallocateMemory(void* Ptr, size_t)
{
    ::operator delete(Ptr, std::align_val_t{ alignment });
}

and that worked, but other issues like string errors were popping up (not using .c_str()) etc... so this is a simpler solution and so far seems to be compiling with no issue:

cmake ..
-DCMAKE_INSTALL_PREFIX=~/twow/tortoise-wow/server \
-DUSE_ANTICHEAT=OFF \
-DALLOW_TURTLE_ADDONS=ON \
-DCMAKE_C_COMPILER=gcc  \
-DCMAKE_CXX_COMPILER=g++
